### PR TITLE
Add approved field to Event model

### LINKED ISSUE #8: Suggest a new event as a guest
As a user, I want to be able to suggest a new event. This will require an admin approving the event before it is shown to the public.

### PR DESCRIPTION
**Pull request by joeriddles**
## Pull Request

**Description:**
- Add an `approved_at` field to the Event model as the first step in allowing guests to suggest a new event.
- Add suggestion form for unauthenticated and non-staff users to suggest a new event, requiring approval by an admin to display the event on the website
- All existing events in the database will be automatically approved via a data migration

**Related Issues:**
- closes #8

**Checklist:**
- [x] All tests pass.
- [x] Code follows the project's coding standards.
- [x] Documentation has been updated.

### CODE REVIEW

**Comment by KGB33** [comment]
When suggesting a group, is there any way to add a picker/selection widget for the duration? Like what the date field has. I ran into some confusion trying to set the duration. 
image

Alternatively, displaying the expected format (`DD:HH:MM`?) would help too. 

Also, I'm not sure if its intentional, but users can suggest events in the past.

Otherwise LGTM.
I like the `Suggest Event` button changing to `Add Event` when logged in as an admin.

**Review by KGB33 — CHANGES_REQUESTED** [review]
See https://github.com/SpokaneTech/SpokaneTech_Py/pull/117#issuecomment-2291985293

**Comment by joeriddles** [comment]
@KGB33 I updated to use two datetime inputs and calculate the difference between them on form save.

image

**Comment by KGB33** [comment]
> @KGB33 I updated to use two datetime inputs and calculate the difference between them on form save.
> 
> image

Looks great!
I don't see it on the branch though.

**Comment by joeriddles** [comment]
> Looks great!
> 
> I don't see it on the branch though.

Remembering to run `git push` would help :) 

Should be there now.

**Review by KGB33 — APPROVED** [review]
LGTM

**Pull request merged**
