### PR TITLE
adding pyptoject.toml and initial code quality workflows

### LINKED ISSUE #12: Determine code styling tools
- Formatter ([black](https://black.readthedocs.io/en/stable/), [ruff](https://docs.astral.sh/ruff/), [isort](https://pycqa.github.io/isort/))
- Linter ([flake8](https://flake8.pycqa.org), [ruff](https://docs.astral.sh/ruff/), [radon](https://radon.readthedocs.io/en/latest/))
- Type checker ([pyright](https://microsoft.github.io/pyright/), [mypy](https://mypy-lang.org/))
- Security ([bandit](https://bandit.readthedocs.io/en/latest/), [safety](https://safetycli.com/product/safety-cli)) 
- Testing (pytest, unittest)

### PR DESCRIPTION
**Pull request by davidslusser**
## Pull Request

**Description:**
Adding pyptoject.toml and initial code quality workflows. I **strongly** recommend using the toml file for tooling parameters to keep configuration consolidated and the root of the repo clean. I added workflows for bandit, black, and ruff (I think we all agree on these). There are many more we can add, but I'll let others take a stab at some before adding more.

**Related Issues:**
- closes #12 

**Checklist:**
- [ ] All tests pass.
- [x] Code follows the project's coding standards.
- [ ] Documentation has been updated.

### CODE REVIEW

**Comment by joeriddles** [comment]
I think the `pyproject.toml` file may have been missed in the commit

**Comment by davidslusser** [comment]
> I think the `pyproject.toml` file may have been missed in the commit

actually, I missed multiple files somehow, doh!

**Comment by joeriddles** [comment]
Noice! Should we just use ruff as both a linter and formatter and drop black altogether? 

https://docs.astral.sh/ruff/formatter/

**Review by joeriddles — APPROVED** [review]

**Comment by davidslusser** [comment]
> Noice! Should we just use ruff as both a linter and formatter and drop black altogether?
> 
> https://docs.astral.sh/ruff/formatter/
> 
> > As such, the formatter is designed as a drop-in replacement for [Black](https://github.com/psf/black), but with an excessive focus on performance and direct integration with Ruff. Given Black's popularity within the Python ecosystem, targeting Black compatibility ensures that formatter adoption is minimally disruptive for the vast majority of projects.



> Noice! Should we just use ruff as both a linter and formatter and drop black altogether?
> 
> https://docs.astral.sh/ruff/formatter/
> 
> > As such, the formatter is designed as a drop-in replacement for [Black](https://github.com/psf/black), but with an excessive focus on performance and direct integration with Ruff. Given Black's popularity within the Python ecosystem, targeting Black compatibility ensures that formatter adoption is minimally disruptive for the vast majority of projects.

I'm open to that. I'll remove it for now, can easily re-add if ppl want more quality tools.

**Pull request merged**
