### PR TITLE
Pyproject.toml -> generated from poetry init

### PR DESCRIPTION
**Pull request by tsarlewey**
I use poetry to generate and add dependencies - this was generated with `poetry init`. Left most of the fields blank for the group to fill out / in.

https://python-poetry.org/

### CODE REVIEW

**Comment by joeriddles** [comment]
Thanks for creating this PR @tsarlewey! We should decide before merging this which Python package management tool we want to use. Options include:
- Just `pip`
- [pip-tools](https://github.com/jazzband/pip-tools)
- [poetry](https://python-poetry.org/)

**Comment by joeriddles** [comment]
@tsarlewey can you update the README docs on how to use poetry for newcomers to the project? If we go the poetry route, we'll want the getting started steps up to date.

**Review by joeriddles — CHANGES_REQUESTED** [review]
See previous comments

**Comment by davidslusser** [comment]
closing this PR as we're moving forward without poetry. If we want to reconsider poetry feel free to make a new PR after confirming with the team.

**Pull request closed without merging**
